StudentsAndTasksASP/Models/Student_has_Tasks.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duble2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_has_Tasks
    {
        [Required]
        [Range(1000, 10000000)]
        public int Student_NumberOfCreditBook { get; set; }
        [Required]
        [Range(1, 10000000)]
        public int Tasks_idTaskNumber { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> TaskPassDate { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> TaskGetDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}

StudentsAndTasksASP/Controllers/Student_has_TasksController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Duble2.Models;
using PagedList;

namespace Duble2.Controllers
{
    public class Student_has_TasksController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Student_has_Tasks
        public ActionResult Index(int? page)
        {
            var student_has_Tasks = db.Student_has_Tasks.Include(s => s.Student).Include(s => s.Tasks);
            student_has_Tasks = student_has_Tasks.OrderBy(x => x.Student_NumberOfCreditBook);

            ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum");
            ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName");

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(student_has_Tasks.ToPagedList(pageNumber, pageSize));
        }

        // GET: Student_has_Tasks/Details/5
        public ActionResult Details(int? id, int? id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student_has_Tasks student_has_Tasks = db.Student_has_Tasks.Find(id,id2);
            if (student_has_Tasks == null)
            {
                return HttpNotFound();
            }
            return View(student_has_Tasks);
        }

        // GET: Student_has_Tasks/Create
        public ActionResult Create()
        {
            ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum");
            ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName");

            //var items = new SelectList(db.Tasks.Include(s => s.Student_has_Tasks).Where(g => g.idTaskNumber != ));

            //ViewBag.Books = new SelectList(items, "GroupNum");

            return View();
        }

        // POST: Student_has_Tasks/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Student_NumberOfCreditBook,Tasks_idTaskNumber,TaskPassDate,TaskGetDate")] Student_has_Tasks student_has_Tasks)
        {
            var results = new List<ValidationResult>();
            var context = new ValidationContext(student_has_Tasks);


            try
            {
                if (Validator.TryValidateObject(student_has_Tasks, context, results, true))
                {
                    if (ModelState.IsValid)
                    {
                        db.Student_TaskInsertProc(student_has_Tasks.Student_NumberOfCreditBook, student_has_Tasks.Tasks_idTaskNumber, student_has_Tasks.TaskPassDate, student_has_Tasks.TaskGetDate);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }


            catch (System.Data.DataException de)
            {
                Exception innerException = de;
                while (innerException.InnerException != null)
                {
                    innerException = innerException.InnerException;
                }
                if (innerException.Message.Contains("Unique_constraint_name"))
                {
                    ModelState.AddModelError(string.Empty, "Error Message");
                    ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum", student_has_Tasks.Student_NumberOfCreditBook);
                    ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName", student_has_Tasks.Tasks_idTaskNumber);
                    return View();
                }
                ModelState.AddModelError(string.Empty, "Error Message");
                ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum", student_has_Tasks.Student_NumberOfCreditBook);
                ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName", student_has_Tasks.Tasks_idTaskNumber);
                return View();
            }

            ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum", student_has_Tasks.Student_NumberOfCreditBook);
            ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName", student_has_Tasks.Tasks_idTaskNumber);
            return View(student_has_Tasks);
        }

        // GET: Student_has_Tasks/Edit/5
        public ActionResult Edit(int? id,int? id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student_has_Tasks student_has_Tasks = db.Student_has_Tasks.Find(id,id2);
            if (student_has_Tasks == null)
            {
                return HttpNotFound();
            }
            ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum", student_has_Tasks.Student_NumberOfCreditBook);
            ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName", student_has_Tasks.Tasks_idTaskNumber);
            return View(student_has_Tasks);
        }

        // POST: Student_has_Tasks/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Student_NumberOfCreditBook,Tasks_idTaskNumber,TaskPassDate,TaskGetDate")] Student_has_Tasks student_has_Tasks)
        {
            var results = new List<ValidationResult>();
            var context = new ValidationContext(student_has_Tasks);


            try
            {

                if (Validator.TryValidateObject(student_has_Tasks, context, results, true))
                {
                    if (ModelState.IsValid)
                    {
                        db.Student_TaskUpdateProc(student_has_Tasks.Student_NumberOfCreditBook, student_has_Tasks.Tasks_idTaskNumber, student_has_Tasks.TaskPassDate, student_has_Tasks.TaskGetDate);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }

            catch (System.Data.DataException de)
            {
                Exception innerException = de;
                while (innerException.InnerException != null)
                {
                    innerException = innerException.InnerException;
                }
                if (innerException.Message.Contains("Unique_constraint_name"))
                {
                    ModelState.AddModelError(string.Empty, "Error Message");
                    ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum", student_has_Tasks.Student_NumberOfCreditBook);
                    ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName", student_has_Tasks.Tasks_idTaskNumber);
                    return View();
                }
                ModelState.AddModelError(string.Empty, "Error Message");
                ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum", student_has_Tasks.Student_NumberOfCreditBook);
                ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName", student_has_Tasks.Tasks_idTaskNumber);
                return View();
            }



            ViewBag.Student_NumberOfCreditBook = new SelectList(db.Student, "NumberOfCreditBook", "Group_2_GroupNum", student_has_Tasks.Student_NumberOfCreditBook);
            ViewBag.Tasks_idTaskNumber = new SelectList(db.Tasks, "idTaskNumber", "Subject_SubjectName", student_has_Tasks.Tasks_idTaskNumber);
            return View(student_has_Tasks);
        }

        // GET: Student_has_Tasks/Delete/5
        public ActionResult Delete(int? id,int? id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student_has_Tasks student_has_Tasks = db.Student_has_Tasks.Find(id, id2);
            if (student_has_Tasks == null)
            {
                return HttpNotFound();
            }
            return View(student_has_Tasks);
        }

        // POST: Student_has_Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id,int id2)
        {
            Student_has_Tasks student_has_Tasks = db.Student_has_Tasks.Find(id,id2);
            db.Student_TaskDeleteProc(student_has_Tasks.Student_NumberOfCreditBook,student_has_Tasks.Tasks_idTaskNumber);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentsAndTasksASP/Views/Student_has_Tasks/Create.cshtml
@model Duble2.Models.Student_has_Tasks

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student_has_Tasks</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Student_NumberOfCreditBook, "Student_NumberOfCreditBook", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Student_NumberOfCreditBook, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Student_NumberOfCreditBook, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tasks_idTaskNumber, "Tasks_idTaskNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tasks_idTaskNumber, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tasks_idTaskNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskPassDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskPassDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskPassDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskGetDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskGetDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskGetDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentsAndTasksASP/Views/Student_has_Tasks/Delete.cshtml
@model Duble2.Models.Student_has_Tasks

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student_has_Tasks</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TaskPassDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskPassDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskGetDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskGetDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Group_2_GroupNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Group_2_GroupNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tasks.Subject_SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tasks.Subject_SubjectName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentsAndTasksASP/Views/Student_has_Tasks/Details.cshtml
@model Duble2.Models.Student_has_Tasks

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student_has_Tasks</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TaskPassDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskPassDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskGetDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskGetDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Group_2_GroupNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Group_2_GroupNum)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Student.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tasks.Subject_SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tasks.Subject_SubjectName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Student_NumberOfCreditBook, id2 = Model.Tasks_idTaskNumber }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StudentsAndTasksASP/Views/Student_has_Tasks/Edit.cshtml
@model Duble2.Models.Student_has_Tasks

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student_has_Tasks</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Student_NumberOfCreditBook)

        @Html.HiddenFor(model => model.Tasks_idTaskNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.TaskPassDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskPassDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskPassDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskGetDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 editor-field">
                @Html.EditorFor(model => model.TaskGetDate)
                @Html.ValidationMessageFor(model => model.TaskGetDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentsAndTasksASP/Views/Student_has_Tasks/Index.cshtml
@model IEnumerable<Duble2.Models.Student_has_Tasks>

@{
    ViewBag.Title = "Учебный план";
}


@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row">
    <div class="col">

    </div>
    <div class="col">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Student.NumberOfCreditBook)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tasks.idTaskNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TaskGetDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TaskPassDate)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Student_NumberOfCreditBook)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tasks.idTaskNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskGetDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskPassDate)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.Student_NumberOfCreditBook ,id2 = item.Tasks_idTaskNumber }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Student_NumberOfCreditBook, id2 = item.Tasks_idTaskNumber }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Student_NumberOfCreditBook, id2 = item.Tasks_idTaskNumber })
                    </td>
                </tr>
            }
        </table>
        <a class="btn btn-primary" href="@Url.Action("Create","Student_has_Tasks")">Learn more &raquo;</a>

        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
    </div>
</div>