StudentsAndTasksASP/Controllers/CurriculaController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Duble2.Models;
using PagedList;

namespace Duble2.Controllers
{
    public class CurriculaController : Controller
    {
        private Entities1 db = new Entities1();
        public string str = "";
        public string str2 = "";
        // GET: Curricula
        public ActionResult Index(int? page)
        {
            var curriculum = db.Curriculum.Include(c => c.Group_2).Include(c => c.Subject);

            curriculum = curriculum.OrderBy(x => x.Group_2_GroupNum);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ViewBag.displayGraph = new SelectList(curriculum);

            return View(curriculum.ToPagedList(pageNumber, pageSize));

        }

        // GET: Curricula/Details/5
        public ActionResult Details(string id,string id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curriculum curriculum = db.Curriculum.Find(id,id2);
            if (curriculum == null)
            {
                return HttpNotFound();
            }
            return View(curriculum);
        }

        // GET: Curricula/Create
        public ActionResult Create()
        {
            ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "GroupNum");
            ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "SubjectName");

            return View();
        }

        // POST: Curricula/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Group_2_GroupNum,Subject_SubjectName")] Curriculum curriculum)
        {
            var results = new List<ValidationResult>();
            var context = new ValidationContext(curriculum);


            try
            {

                if (Validator.TryValidateObject(curriculum, context, results, true))
                {
                    if (ModelState.IsValid)
                    {
                        db.CurriculumInsertProc1(curriculum.Group_2_GroupNum, curriculum.Subject_SubjectName);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }

            catch (System.Data.DataException de)
            {
                Exception innerException = de;
                while (innerException.InnerException != null)
                {
                    innerException = innerException.InnerException;
                }
                if (innerException.Message.Contains("Unique_constraint_name"))
                {
                    ModelState.AddModelError(string.Empty, "Error Message");
                    ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "GroupNum", curriculum.Group_2_GroupNum);

                    ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "SubjectName", curriculum.Subject_SubjectName);
                    return View();
                }
                ModelState.AddModelError(string.Empty, "Error Message");

                ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "GroupNum", curriculum.Group_2_GroupNum);

                ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "SubjectName", curriculum.Subject_SubjectName);

                return View();
            }

            ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "GroupNum", curriculum.Group_2_GroupNum);

            ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "SubjectName", curriculum.Subject_SubjectName);

            return View(curriculum);
        }

        // GET: Curricula/Edit/5
        public ActionResult Edit(string id, string id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            str = id;
            str2 = id2;
            Curriculum curriculum = db.Curriculum.Find(id,id2);

            ViewBag.Message = id2;

            str = curriculum.Group_2_GroupNum;
            str2 = curriculum.Subject_SubjectName;
            if (curriculum == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "GroupNum", curriculum.Group_2_GroupNum);

            ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "SubjectName", curriculum.Subject_SubjectName);

            return View(curriculum);
        }

        // POST: Curricula/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Group_2_GroupNum,Subject_SubjectName")] Curriculum curriculum, string PlayerID)
        {
            var results = new List<ValidationResult>();
            var context = new ValidationContext(curriculum);



            if (Validator.TryValidateObject(curriculum, context, results, true))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        var g = db.CurriculumUpdateProc(curriculum.Group_2_GroupNum, PlayerID, curriculum.Subject_SubjectName);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (System.Data.DataException de)
                    {
                        Exception innerException = de;
                        while (innerException.InnerException != null)
                        {
                            innerException = innerException.InnerException;
                        }


                        if (innerException.Message.Contains("Unique_constraint_name"))
                        {
                            ModelState.AddModelError(string.Empty, "Error Message");
                            ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "MajorName", curriculum.Group_2_GroupNum);
                            ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "TeachersFIO", curriculum.Subject_SubjectName);

                            return View();
                        }



                        ModelState.AddModelError(string.Empty, "Error Message");

                        ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "MajorName", curriculum.Group_2_GroupNum);
                        ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "TeachersFIO", curriculum.Subject_SubjectName);

                        return View();
                    }

                }
            }
            ViewBag.Group_2_GroupNum = new SelectList(db.Group_2, "GroupNum", "MajorName", curriculum.Group_2_GroupNum);

            ViewBag.Subject_SubjectName = new SelectList(db.Subject, "SubjectName", "TeachersFIO", curriculum.Subject_SubjectName);




            return View(curriculum);
        }


        // GET: Curricula/Delete/5
        public ActionResult Delete(string id, string id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curriculum curriculum = db.Curriculum.Find(id,id2);
            if (curriculum == null)
            {
                return HttpNotFound();
            }
            return View(curriculum);
        }

        // POST: Curricula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id, string id2)
        {
            Curriculum curriculum = db.Curriculum.Find(id,id2);
            db.CurriculumDeleteProc(curriculum.Group_2_GroupNum,curriculum.Subject_SubjectName);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

StudentsAndTasksASP/Views/Curricula/Create.cshtml
@model Duble2.Models.Curriculum

@{
    ViewBag.Title = "Добавление";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Curriculum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Group_2_GroupNum, "Group_2_GroupNum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Group_2_GroupNum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Group_2_GroupNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject_SubjectName, "Subject_SubjectName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Subject_SubjectName", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Subject_SubjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentsAndTasksASP/Views/Curricula/Delete.cshtml
@model Duble2.Models.Curriculum

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Curriculum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Group_2.MajorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group_2.MajorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject.TeachersFIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.TeachersFIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject1.TeachersFIO)
        </dt>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentsAndTasksASP/Views/Curricula/Details.cshtml
@model Duble2.Models.Curriculum

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Curriculum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Group_2.GroupNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group_2.GroupNum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Subject_SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject_SubjectName)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Group_2_GroupNum,id2 = Model.Subject_SubjectName  }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StudentsAndTasksASP/Views/Curricula/Edit.cshtml
@model Duble2.Models.Curriculum

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Curriculum</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Group_2_GroupNum, "Group_2_GroupNum", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Group_2_GroupNum", null, htmlAttributes: new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.Group_2_GroupNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Subject_SubjectName, "Subject_SubjectName", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Subject_SubjectName", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Subject_SubjectName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
         
        <div class="col-md-offset-2 col-md-10">
            <input type="hidden" name="PlayerID" id="PlayerID" value="@ViewBag.Message" />
            <input type="submit" id="PlayerID" name="PlayerID" value="Edit" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentsAndTasksASP/Views/Curricula/Index.cshtml
@model PagedList.PagedList<Duble2.Models.Curriculum>

@{
    ViewBag.Title = "Учебный план";
}

@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row">
    <div class="col">

    </div>
    <div class="col">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Group_2_GroupNum)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Subject_SubjectName)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @Html.DisplayFor(modelItem => item.Group_2_GroupNum)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.Subject_SubjectName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Group_2_GroupNum, id2 = item.Subject_SubjectName }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Group_2_GroupNum, id2 = item.Subject_SubjectName }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Group_2_GroupNum, id2 = item.Subject_SubjectName })
                    </td>
                </tr>
            }
        </table>

        <a class="btn btn-primary" href="@Url.Action("Create","Curricula")">Create &raquo;</a>

        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
    </div>
</div>