StudentsAndTasksASP/Controllers/Task1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Duble2.Models;
using PagedList;

namespace Duble2.Controllers
{
    public class Task1Controller : Controller
    {
        private Entities1 db = new Entities1();

        private string oldGroupnum = "";

        public ActionResult Index(string groupNum,string oldGroupNum, int? page)
        {
            if (groupNum != null )
            {
                page = 1;
            }
            else
            {
                groupNum = oldGroupNum;

            }
               ViewBag.oldGroupNum = groupNum;

            var g = db.TaskOneProc(groupNum).OrderBy(x => x.SubjectName).ToList();

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(g.ToPagedList(pageNumber, pageSize));
        }     
    }
}

StudentsAndTasksASP/Views/Task1/Index.cshtml
@model PagedList<Duble2.Models.TaskOneProc_Result>

@{
    ViewBag.Title = "Количество заданий";
}

@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>@ViewBag.Title</h2>


<div class="row mb-4">
    <div class="col-md-8 ">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Group_2_GroupNum)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().NumberOfCreditBook)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().FIO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().SubjectName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().count)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Group_2_GroupNum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberOfCreditBook)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FIO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubjectName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.count)
                    </td>
                </tr>
            }

        </table>
        <div>
            @using (Html.BeginForm("Index", "Task1", FormMethod.Post))
            {
                <table>
                    <tr>
                        <td><p>Группа</p></td>
                        <td><input type="text" name="groupNum" /></td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Найти" /></td>
                        <td></td>
                    </tr>

                </table>
            }
        </div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SizePage = @Model.PageSize, oldGroupNum = ViewBag.oldGroupNum }))
    </div>
</div>